In [8]:
import pandas as pd

In [9]:
pd.read_json("train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [10]:
pd.read_json("https://raw.githubusercontent.com/sharmadhiraj/free-json-datasets/refs/heads/master/datasets/nepse-listed-companies-2021.json")

,name,symbol,category,logo
0,10 % NMB DEBENTURE 2085,NMBD2085,Corporate Debenture,
1,10% Himalayan Bank Debenture 2083,HBLD83,Corporate Debenture,
2,10% Laxmi Bank Debenture 2086,LBLD86,Corporate Debenture,
3,10% Nabil Debenture 2082,NBLD82,Corporate Debenture,
4,10% Nepal SBI Bank Debenture 2086,SBIBD86,Corporate Debenture,
...,...,...,...,...
321,Upper Tamakoshi Hydropower Ltd,UPPER,Hydro Power,http://www.nepalstock.com/uploads/images/compa...
322,Vijaya laghubitta Bittiya Sanstha Ltd.,VLBS,Microfinance,http://www.nepalstock.com/uploads/images/compa...
323,Wean Nepal Laghubitta Bittiya Sanstha Limited,WNLB,Microfinance,http://www.nepalstock.com/uploads/images/compa...
324,Womi Microfinance Bittiya Sanstha Ltd.,WOMI,Microfinance,http://www.nepalstock.com/uploads/images/compa...
325,Yak And Yeti Hotel Limited,YHL,Hotels,

### Working with SQL

In [11]:
!pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql.connector in c:\users\salman pc\appdata\roaming\python\python313\site-packages (2.2.9)

In [12]:
import mysql.connector

In [13]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world')

In [14]:
pd.read_sql_query("SELECT * FROM city", conn)

C:\Users\Salman PC\AppData\Local\Temp\ipykernel_12064\1432342221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city", conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]